language: objective-c
xcode_workspace: CircleCI-Sample.xcworkspace
xcode_scheme: CircleCI-Sample
xcode_sdk: iphonesimulator
cache: bundler
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'