language: objective-c
xcode_workspace: CircleCI-Sample.xcworkspace
xcode_scheme: CircleCI-Sample
xcode_sdk: iphonesimulator
osx_image: xcode7.3
cache: bundler
services:
  - mysql
  - postgresql
before_install:
  - brew update
  - brew services start postgresql
  - brew install mysql
  - brew services start mysql
env:
  matrix:
    - TEST_TARGET=test1
    - TEST_TARGET=test2
script:
  - travis_wait 30 xctool -workspace CircleCI-Sample.xcworkspace -scheme CircleCI-Sample -sdk iphonesimulator build $TEST_TARGET
