language: objective-c
xcode_workspace: CircleCI-Sample.xcworkspace
xcode_scheme: CircleCI-Sample
xcode_sdk: iphonesimulator
cache: bundler
services:
  - mysql
  - postgresql
before_install:
  - brew update
  - brew services stop postgresql
  - brew services start postgresql
  - brew info mysql