language: objective-c
xcode_workspace: CircleCI-Sample.xcworkspace
xcode_scheme: CircleCI-Sample
xcode_sdk: iphonesimulator
cache: bundler
services:
  - mysql
  - postgresql
before_install:
  - brew update
  - brew install language-pack-es
  - /etc/init.d/postgresql stop
  - /etc/init.d/postgresql start 9.3