language: objective-c
xcode_workspace: CircleCI-Sample.xcworkspace
xcode_scheme: CircleCI-Sample
xcode_sdk: iphonesimulator
cache: bundler
services:
  - mysql
  - postgresql
before_install:
  - apt-get update
  - apt-get install language-pack-es
  - /etc/init.d/postgresql stop
  - /etc/init.d/postgresql start 9.3
  - psql -c 'create database travis_ci_test;' -U postgres