language: objective-c
xcode_workspace: CircleCI-Sample.xcworkspace
osx_image: xcode8
env: TEST_SUITE=suite_8
xcode_scheme: CircleCI-Sample
xcode_sdk: iphonesimulator
cache: bundler
services:
  - mysql
  - postgresql
before_install:
  - brew update
  - brew services start postgresql
  - brew install mysql
  - brew services start mysql
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env: TEST_SUITE=suite_7_3