language: objective-c
xcode_workspace: CircleCI-Sample.xcworkspace
xcode_scheme: CircleCI-Sample
xcode_sdk: iphonesimulator
cache: bundler
services:
  - mysql
  - postgresql
before_install:
  - brew update
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres